services:
  - type: web
    name: the-cloth-store
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn ClothStore.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ClothStore.settings