# Generated by Django 4.2.7 on 2023-11-29 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_image', models.ImageField(default=None, upload_to='Prod_Images')),
                ('product_description', models.TextField()),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gender', models.CharField(choices=[('men', 'MEN'), ('women', 'WOMEN'), ('unisex', 'UNISEX')], max_length=20)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ClothApp.category')),
            ],
        ),
    ]
